### ISSUE TITLE
Feature: Ecommerce Template

### ISSUE THREAD

**Issue by Horizon733** [Hiten24/Compose-Ui-Templates#13]
Can anyone add an eCommerce template, it would really look good. below is a reference from Behance please have a look at it:
<br>
<img src="https://images-ext-2.discordapp.net/external/QCfRhsBr7TB2Q-ui__Ch-aq8_pR8vRtC3XFoFogGIFo/https/mir-s3-cdn-cf.behance.net/project_modules/1400/675066127508245.61432cd53635b.png?width=627&height=499">

**Comment by Hiten24** [comment]
Thanks for the suggestion, I'll add that
