### ISSUE TITLE
Feature: adding icon for our app

### ISSUE THREAD

**Issue by Horizon733** [Hiten24/Compose-Ui-Templates#24]
Hi, I also want to add a good icon for our app, since android icon does look good, I will share some ideas that I found here, please add your thoughts

**Comment by Rishavgupta12345** [comment]
can i work on this issue ?

**Comment by Hiten24** [comment]
@Horizon733 was the first to identify this issue, I'm giving them a chance to claim this first if they want. Let's see what @Horizon733 says :)

**Comment by Rishavgupta12345** [comment]
it will hardly take 5 minutes to solve this issue .
i dont know why it is still on progress form 2 days .

**Comment by Hiten24** [comment]
I like the 4th one
