### ISSUE TITLE
Bug: Textfeild hint

### ISSUE THREAD

**Issue by Hiten24** [Hiten24/Compose-Ui-Templates#4]
![image](https://user-images.githubusercontent.com/48350702/135711659-5cc68354-d228-41cd-ba81-05ff2aa30371.png)

There is no hint in the message text feild

**Comment by Biren-Nayak** [comment]
@Hiten24 I am able to find the problem and I am currently working on it, kindly assign me to this issue.

**Comment by Hiten24** [comment]
Sure
